#!/bin/bash

set +e

/usr/lib/xdg-desktop-portal-wlr &
/usr/lib/xdg-desktop-portal-gtk &
/usr/lib/xdg-desktop-portal-gnome &
/usr/lib/xdg-desktop-portal-kde &
/usr/lib/xdg-desktop-portal-rewrite-launchers &
/usr/lib/xdg-document-portal &
/usr/lib/xdg-permission-store &
/usr/lib/xdg-desktop-portal &
